
server:  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/alexmdo/Alura-Microservices-com-Spring-Cloud-Registry-Config-Server-e-Distributed-Tracing
          search-paths: config
          default-label: main